import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
Color primaryColor = const Color(0xFF0C2461);
Color Subthintextcolor = const Color(0xFF999999);
Color borders = const Color(0xFFF4F4F4);
Color Butn = const Color(0xFF00926E);
Color thirdreuseclktext =  Color(0xFFE0115F);
Color textfield = const Color(0xFFA1A1A1);
Color map = const Color(0xFF00926E);
Color otpbox = const Color(0xFFF4F4F4);
Color otbfiedl = const Color(0xFFE0115F);
Color searcecolor = const Color(0xFFcae0f2);
Color boxscoll = const Color(0xFF00926E);
Color otherboxscoll = const Color(0xFFF2F5FD);
Color sliderhome = const Color(0xFFD9D9D9);
Color producthome = const Color(0xFFF2F5FD);
Color bastcolor= const Color(0xFFB41212);
Color favritescolor= const Color(0xFF00926E);
Color artcolor= const Color(0xFFF2F5FD);
Color basket= const Color(0xFFF2F5FD);
Color basketadd= const Color(0xFF0C2461);
const Color liklypink = Color(0xff92278f);//AB9D82
const Color colorAccent = Color(0xff00aeef);//DF125F
const Color colorFirsttahade = Color(0xffDF125F);
const Color colorSecondtahade = Color(0xff09B1FC);
const Color colorthamry = Color(0xff8E3E00);//#FD96CE
const Color colorforpicksream = Color(0xffFD96CE);//#
Color grey50 = Colors.grey.shade50;
Color grey100 = Colors.grey.shade100;
Color grey200 = Colors.grey.shade200;
Color grey300 = Colors.grey.shade300;
Color grey400 = Colors.grey.shade400;
Color grey500 = Colors.grey.shade500;
Color grey600 = Colors.grey.shade600;
Color grey700 = Colors.grey.shade700;
Color grey800 = Colors.grey.shade800;
Color grey900 = Colors.grey.shade900;
Color background = Colors.white;
// Color background = Colors.grey.shade100;
const Color green = Colors.green;
const Color red = Colors.red;
const Color blue = Colors.blue;
Color Thintextcolor = const Color(0xFF0C2461);
const Color black = Colors.black;
const Color orange = Colors.orange;
const Color gold = Color(0xffe8b923);//FFD700
const Color gold2 = Color(0xffB59410);//1E202D
const Color stackholderbackground = Color(0xff1E202D);//
Color blackWithOpacity50 = Colors.black.withOpacity(0.5);
Color blackWithOpacity30 = Colors.black.withOpacity(0.3);
Color whiteWithOpacity50 = white.withOpacity(0.5);
Color whiteWithOpacity30 = white.withOpacity(0.3);
const Color white = Colors.white;//1E202D
const Color transparent = Colors.transparent;
Color shimmerBaseColor = Colors.grey.shade200;
Color shimmerHighlightColor = Colors.grey.shade100;

